.phony: all clean
 
all: Historian_Hysteria

CPP = g++
CPPFLAGS = -Wall -Wextra -std=c++17 -O3

Historian_Hysteria: Historian_Hysteria.cpp
	$(CPP) Historian_Hysteria.cpp -o Historian_Hysteria $(CPPFLAGS)



clean:
	rm -f *.o Historian_Hysteria 