.phony: all clean
 
all: Ceres_Search

CPP = g++
CPPFLAGS = -Wall -Wextra -std=c++17 -O3

Ceres_Search: Ceres_Search.cpp
	$(CPP) Ceres_Search.cpp -o Ceres_Search $(CPPFLAGS)



clean:
	rm -f *.o Ceres_Search 